// Sample data for Unitrade prototype — UNILAG-flavored
window.UT_DATA = {
  university: { name: "University of Lagos", short: "UNILAG", city: "Akoka, Lagos" },
  currentUser: {
    id: "u_self",
    name: "Tomi A.",
    handle: "tomi.a",
    dept: "Mass Comm '26",
    rating: 4.8,
    deals: 14,
    verified: true,
    avatar: "TA",
  },
  categories: [
    { id: "books", label: "Textbooks", icon: "book" },
    { id: "electronics", label: "Electronics", icon: "chip" },
    { id: "fashion", label: "Fashion", icon: "shirt" },
    { id: "furniture", label: "Hostel", icon: "bed" },
    { id: "services", label: "Services", icon: "spark" },
  ],
  listings: [
    {
      id: "l_01",
      title: "Schaum's Outline — Calculus (3rd Ed.)",
      price: 3500,
      negotiable: true,
      condition: "Good",
      category: "books",
      tradeable: true,
      escrow: true,
      tags: ["MTH 101", "engineering"],
      seller: { id: "u_kemi", name: "Kemi O.", dept: "EEE '25", rating: 4.9, deals: 22, avatar: "KO" },
      hall: "Mariere Hall",
      posted: "2h ago",
      saves: 18,
      blurb: "Used for one semester. Some highlighter on chapter 4 — otherwise crisp. Cash or swap for a 200L Mech textbook.",
      swatch: "ink",
      slug: "📕",
    },
    {
      id: "l_02",
      title: "MacBook Air M1 — 8GB / 256GB",
      price: 520000,
      negotiable: true,
      condition: "Excellent",
      category: "electronics",
      tradeable: false,
      escrow: true,
      tags: ["laptop", "battery 92%"],
      seller: { id: "u_dami", name: "Dami T.", dept: "CSC '24", rating: 5.0, deals: 41, avatar: "DT" },
      hall: "Off-campus · Yaba",
      posted: "5h ago",
      saves: 64,
      blurb: "Final-year, upgrading to a Pro. Battery cycle 142. Comes with original 30W charger and a sleeve.",
      swatch: "silver",
      slug: "💻",
    },
    {
      id: "l_03",
      title: "Reading Lamp + Power Bank Bundle",
      price: 6800,
      negotiable: false,
      condition: "Like new",
      category: "furniture",
      tradeable: true,
      escrow: false,
      tags: ["NEPA-friendly", "USB-C"],
      seller: { id: "u_seun", name: "Seun B.", dept: "Law '27", rating: 4.7, deals: 9, avatar: "SB" },
      hall: "Queen Amina Hall",
      posted: "yesterday",
      saves: 11,
      blurb: "Bought from Computer Village. Lamp is dimmable. 10,000 mAh power bank — fast charges most phones in 90 mins.",
      swatch: "amber",
      slug: "🔆",
    },
    {
      id: "l_04",
      title: "Ankara Two-Piece — Size M",
      price: 9500,
      negotiable: true,
      condition: "Worn once",
      category: "fashion",
      tradeable: true,
      escrow: false,
      tags: ["matric", "tailored"],
      seller: { id: "u_ada", name: "Ada N.", dept: "Pharm '25", rating: 4.8, deals: 17, avatar: "AN" },
      hall: "Moremi Hall",
      posted: "1d ago",
      saves: 29,
      blurb: "Custom tailored for matriculation. Open to a swap for size S Ankara or pay top-up.",
      swatch: "rose",
      slug: "👗",
    },
    {
      id: "l_05",
      title: "Stats Tutoring · STA 121 / 211",
      price: 2000,
      priceUnit: "/ session",
      negotiable: false,
      condition: "Service",
      category: "services",
      tradeable: false,
      escrow: true,
      tags: ["1-on-1", "weekends"],
      seller: { id: "u_jide", name: "Jide F.", dept: "Stats '24", rating: 4.9, deals: 36, avatar: "JF" },
      hall: "Library · Block C",
      posted: "Today",
      saves: 8,
      blurb: "First class Stats finalist. 90-min sessions, includes past questions. Group of 3+ gets ₦500 off each.",
      swatch: "olive",
      slug: "📊",
    },
    {
      id: "l_06",
      title: "Mini Fridge — 50L, quiet",
      price: 42000,
      negotiable: true,
      condition: "Used 1yr",
      category: "furniture",
      tradeable: false,
      escrow: true,
      tags: ["pickup only", "Akoka"],
      seller: { id: "u_chiamaka", name: "Chiamaka E.", dept: "Acct '24", rating: 4.6, deals: 12, avatar: "CE" },
      hall: "Off-campus · Akoka",
      posted: "3d ago",
      saves: 22,
      blurb: "Moving out after final defense. Cools fast, low noise. You arrange pickup — I'll help carry to the gate.",
      swatch: "ice",
      slug: "🧊",
    },
    {
      id: "l_07",
      title: "iPhone 12 — 128GB, Blue",
      price: 285000,
      negotiable: true,
      condition: "Fair",
      category: "electronics",
      tradeable: true,
      escrow: true,
      tags: ["face ID ok", "85% battery"],
      seller: { id: "u_femi", name: "Femi A.", dept: "Med '23", rating: 4.7, deals: 28, avatar: "FA" },
      hall: "CMUL · Idi-Araba",
      posted: "6h ago",
      saves: 53,
      blurb: "Small hairline on the back glass — screen is clean. Open to swap + cash for a Pixel 7 or newer.",
      swatch: "ocean",
      slug: "📱",
    },
    {
      id: "l_08",
      title: "Engineering Drawing Set + T-square",
      price: 4200,
      negotiable: false,
      condition: "Good",
      category: "books",
      tradeable: true,
      escrow: false,
      tags: ["100L", "Staedtler"],
      seller: { id: "u_bayo", name: "Bayo K.", dept: "Civ Eng '26", rating: 4.9, deals: 7, avatar: "BK" },
      hall: "Faculty of Eng",
      posted: "2d ago",
      saves: 14,
      blurb: "Complete set — compass, set squares, protractor. T-square has a small chip on the edge but works fine.",
      swatch: "ink",
      slug: "📐",
    },
  ],
  messages: [
    {
      id: "m_01",
      with: { name: "Kemi O.", avatar: "KO", dept: "EEE '25" },
      listingId: "l_01",
      listingTitle: "Schaum's Outline — Calculus",
      lastSnippet: "Sure, I can meet at New Hall by 4pm 👍",
      unread: 1,
      ts: "12:42",
      thread: [
        { from: "them", t: "Hey! Saw your listing. Still available?", at: "11:58" },
        { from: "me", t: "Yes! Still here. Are you cash or trade?", at: "12:04" },
        { from: "them", t: "Cash. Can we meet today?", at: "12:30" },
        { from: "me", t: "Yeah — what time works?", at: "12:36" },
        { from: "them", t: "Sure, I can meet at New Hall by 4pm 👍", at: "12:42" },
      ],
    },
    {
      id: "m_02",
      with: { name: "Dami T.", avatar: "DT", dept: "CSC '24" },
      listingId: "l_02",
      listingTitle: "MacBook Air M1",
      lastSnippet: "Escrow is fine by me. I'll confirm once you fund.",
      unread: 0,
      ts: "Yesterday",
      thread: [
        { from: "me", t: "Hi Dami — would you do 490k?", at: "Yesterday" },
        { from: "them", t: "I can come down to 505k, that's my final.", at: "Yesterday" },
        { from: "them", t: "Escrow is fine by me. I'll confirm once you fund.", at: "Yesterday" },
      ],
    },
    {
      id: "m_03",
      with: { name: "Ada N.", avatar: "AN", dept: "Pharm '25" },
      listingId: "l_04",
      listingTitle: "Ankara Two-Piece",
      lastSnippet: "Swap proposal sent — see details.",
      unread: 2,
      ts: "Mon",
      thread: [
        { from: "them", t: "Hi! Open to a swap?", at: "Mon" },
        { from: "me", t: "Depends — what do you have?", at: "Mon" },
        { from: "them", t: "Swap proposal sent — see details.", at: "Mon" },
      ],
    },
  ],
};
