export const NIGERIAN_UNIVERSITIES = [
  // Federal Universities
  "University of Lagos (UNILAG)",
  "University of Ibadan (UI)",
  "Obafemi Awolowo University (OAU)",
  "University of Nigeria, Nsukka (UNN)",
  "Ahmadu Bello University (ABU)",
  "University of Benin (UNIBEN)",
  "University of Port Harcourt (UNIPORT)",
  "University of Ilorin (UNILORIN)",
  "University of Maiduguri (UNIMAID)",
  "University of Calabar (UNICAL)",
  "Bayero University Kano (BUK)",
  "University of Jos (UNIJOS)",
  "University of Abuja (UNIABUJA)",
  "Usmanu Danfodiyo University Sokoto (UDUS)",
  "Abubakar Tafawa Balewa University (ATBU)",
  "Nnamdi Azikiwe University (UNIZIK)",
  "Federal University of Technology, Akure (FUTA)",
  "Federal University of Technology, Minna (FUTMINNA)",
  "Federal University of Technology, Owerri (FUTO)",
  "Federal University of Agriculture, Abeokuta (FUNAAB)",
  "Michael Okpara University of Agriculture, Umudike (MOUAU)",
  "Federal University Oye-Ekiti (FUOYE)",
  "Federal University Dutse (FUD)",
  "Federal University Lafia (FULAFIA)",
  "Federal University Gashua (FUGASHUA)",
  "Federal University Birnin Kebbi (FUBK)",
  "Federal University Wukari (FUWUKARI)",
  "Federal University Lokoja (FULOKOJA)",
  "Federal University Kashere (FUKASHERE)",
  "Federal University Otuoke (FUOTUOKE)",
  "Alex Ekwueme Federal University Ndufu-Alike (AE-FUNAI)",
  "Federal University Dutsin-Ma (FUDMA)",
  "Nigerian Defence Academy (NDA)",
  "National Open University of Nigeria (NOUN)",
  "Air Force Institute of Technology (AFIT)",
  "Nigerian Army University Biu (NAUB)",

  // State Universities
  "Lagos State University (LASU)",
  "Lagos State University of Science and Technology (LASUSTECH)",
  "Tai Solarin University of Education (TASUED)",
  "Olabisi Onabanjo University (OOU)",
  "Ladoke Akintola University of Technology (LAUTECH)",
  "Osun State University (UNIOSUN)",
  "Ekiti State University (EKSU)",
  "Adekunle Ajasin University (AAUA)",
  "Ondo State University of Science and Technology (OSUSTECH)",
  "Kwara State University (KWASU)",
  "Rivers State University (RSU)",
  "Imo State University (IMSU)",
  "Delta State University (DELSU)",
  "Enugu State University of Science and Technology (ESUT)",
  "Ambrose Alli University (AAU)",
  "Kogi State University (KSU)",
  "Confluence University of Science and Technology (CUSTECH)",
  "Benue State University (BSU)",
  "Plateau State University (PLASU)",
  "Taraba State University (TSU)",
  "Gombe State University (GSU)",
  "Yobe State University (YSU)",
  "Umar Musa Yar'adua University (UMYU)",
  "Ibrahim Babangida University Lapai (IBBU)",
  "Kaduna State University (KASU)",
  "Kebbi State University of Science and Technology (KSUSTA)",
  "Sokoto State University (SSU)",
  "Zamfara State University",
  "Katsina University (KTU)",
  "Modibbo Adama University of Technology (MAUTECH)",
  "Adamawa State University (ADSU)",
  "Bauchi State University Gadau (BASUG)",
  "Borno State University (BOSU)",
  "Abia State University (ABSU)",
  "Ebonyi State University (EBSU)",
  "Chukwuemeka Odumegwu Ojukwu University (COOU)",
  "Akwa Ibom State University (AKSU)",
  "Cross River University of Technology (CRUTECH)",
  "Nasarawa State University (NSU)",
  "Niger State University (NSUK)",
  "Bayelsa Medical University (BMU)",

  // Private Universities
  "Covenant University",
  "Babcock University",
  "Redeemer's University",
  "Bowen University",
  "American University of Nigeria (AUN)",
  "Lead City University",
  "Pan-Atlantic University (PAU)",
  "Landmark University",
  "Benson Idahosa University",
  "Igbinedion University Okada",
  "Madonna University",
  "Afe Babalola University (ABUAD)",
  "Bells University of Technology",
  "Joseph Ayo Babalola University (JABU)",
  "Elizade University",
  "Oduduwa University",
  "Achievers University",
  "Crawford University",
  "Caleb University",
  "Crescent University",
  "Al-Hikmah University",
  "Salem University",
  "Caritas University",
  "Gregory University",
  "Novena University",
  "Rhema University",
  "Veritas University",
  "Dominion University",
  "Edwin Clark University",
  "Evangel University",
  "Godfrey Okoye University",
  "Nile University of Nigeria",
  "Paul University",
  "Samuel Adegboyega University",
  "Tansian University",
  "Western Delta University",
  "Renaissance University",
  "Hallmark University",
  "Spiritan University Nneochi",
  "Hezekiah University",
  "Kola Daisi University",
  "McPherson University",
  "Wesley University",
  "Mountain Top University",
  "Adeleke University",
  "Anchor University",
  "Ajayi Crowther University",
  "Chrisland University",
  "Clifford University",
  "Thomas Adewumi University",
  "Precious Cornerstone University",
  "Baze University",
  "Eastern Palm University",
  "Edusoko University",
  "Dennis Osadebay University",
  "Legacy University",
  "Oasis Medical University",
  "Summit University",
] as const;
