/**
 * Shared SEO primitives.
 *
 * Every page used to re-derive the canonical origin from process.env inline,
 * which made it easy to drift. Import APP_URL / absoluteUrl from here instead.
 */

export const APP_URL =
  process.env.APP_URL?.startsWith("http")
    ? process.env.APP_URL
    : "https://kolejswap.com";

export function absoluteUrl(path = "/"): string {
  if (path.startsWith("http")) return path;
  // The root canonical is the bare origin, so "/" must not add a trailing
  // slash — otherwise the sitemap and the <link rel="canonical"> disagree.
  if (path === "/" || path === "") return APP_URL;
  return `${APP_URL}${path.startsWith("/") ? path : `/${path}`}`;
}

/**
 * Default social / search preview card, generated by app/opengraph-image.tsx.
 *
 * Next injects the file-convention image automatically, but ONLY into routes
 * that do not declare their own `openGraph` object — declaring one replaces the
 * inherited value wholesale. Any page that sets `openGraph` must therefore
 * spread DEFAULT_OG_IMAGES back in, or it ships with no preview image at all.
 */
export const DEFAULT_OG_IMAGES = [
  {
    url: absoluteUrl("/opengraph-image"),
    width: 1200,
    height: 630,
    alt: "KolejSwap — buy, sell and swap at Nigerian universities",
  },
];

/**
 * XML-escape a URL for use in a sitemap <loc>.
 *
 * Next's sitemap serializer interpolates `item.url` straight into the XML with
 * no escaping (see build/webpack/loaders/metadata/resolve-route-data), so a URL
 * carrying a query string with `&` produces a sitemap Google rejects as
 * malformed. Escaping here is the only place it can happen.
 */
export function sitemapUrl(path: string): string {
  return absoluteUrl(path)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

export type Crumb = { name: string; path: string };

export function breadcrumbLd(trail: Crumb[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: trail.map((crumb, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: crumb.name,
      item: absoluteUrl(crumb.path),
    })),
  };
}

export type Faq = { q: string; a: string };

export function faqLd(faqs: Faq[]) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((faq) => ({
      "@type": "Question",
      name: faq.q,
      acceptedAnswer: { "@type": "Answer", text: faq.a },
    })),
  };
}

export type LdListing = {
  id: string;
  title: string;
  price: number | string;
  images?: string[] | null;
  url: string;
};

/**
 * ItemList of listings. Google uses this to understand that a page is a
 * collection of offers rather than a single product, which is what keeps
 * category and landing pages out of the "thin page" bucket.
 */
export function itemListLd({
  name,
  path,
  description,
  items,
}: {
  name: string;
  path: string;
  description?: string;
  items: LdListing[];
}) {
  return {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    name,
    url: absoluteUrl(path),
    ...(description ? { description } : {}),
    isPartOf: { "@type": "WebSite", name: "KolejSwap", url: APP_URL },
    mainEntity: {
      "@type": "ItemList",
      numberOfItems: items.length,
      itemListElement: items.map((item, i) => ({
        "@type": "ListItem",
        position: i + 1,
        item: {
          "@type": "Product",
          name: item.title,
          url: absoluteUrl(item.url),
          ...(item.images?.[0] ? { image: item.images[0] } : {}),
          offers: {
            "@type": "Offer",
            priceCurrency: "NGN",
            price: Number(item.price).toFixed(2),
            availability: "https://schema.org/InStock",
            url: absoluteUrl(item.url),
          },
        },
      })),
    },
  };
}

/**
 * Faceted catalog URLs (search text, sort order, price caps, condition…) are
 * near-duplicates of the unfiltered page. Let Google follow them for discovery
 * but keep them out of the index so crawl budget lands on real pages.
 */
export const NOINDEX_FOLLOW = { index: false, follow: true } as const;
